
name: Horusec

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:
        
jobs:
  horusec-security:
    name: Horusec
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with: 
        fetch-depth: 0
    - name: Running Horusec Security
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
        # horusec start -p="./" -e="true" -o="json" -O="./horusec-report.json"
        horusec start -p="./" --config-file-path=".github/workflows/horusec-config.json"
    - name: Upload Horusec Report
      if: always()
      uses: actions/upload-artifact@v3.1.0
      with:
        name: horusec-report
        path: horusec-report.json
