
name: Security Pipeline

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
        
jobs:
  horusec-security:
    name: horusec-security
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      with: # Required when commit authors is enabled
        fetch-depth: 0
    - name: Running Horusec Security
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest
        # horusec start -p="./" -e="true" -o="json" -O="./horusec-report.json"
    - name: Upload Horusec Report
      if: always()
      uses: actions/upload-artifact@v3.1.0
      with:
        name: horusec-report
        # A file, directory or wildcard pattern that describes what to upload
        path: horusec-report.json
